name: list_tile_switch
description: A new Flutter package for ListTileSwitch.
version: 0.0.1
author: f1r4tc@gmail.com
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
